import "../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { FaUserAlt } from "react-icons/fa";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex justify-between flex-row items-center px-[15px] md:px-[30px] xl:px-[50px] 2xl:px-[100px] mx-auto py-[10px] z-50 w-full absolute top-0 left-0 right-0">
          <div className="flex items-center">
            <div>
              {/* <a href="/home" className="">
                <img
                  src="https://streamo.vuejstemplate.com/images/logo/logo.png"
                  alt="Logo"
                />
              </a> */}
              <Link href="/" className="flex items-center gap-4">
                {/* <Image
                  src="/assets/logo.svg"
                  alt="logo"
                  width={28}
                  height={28}
                /> */}
                <p className=" text-light-1 max-xs:hidden text-heading3-bold font-semibold uppercase">
                  Logo
                </p>
              </Link>
            </div>
          </div>
          <div className="flex items-center">
            <div className="ml-[10px] sm:ml-[15px]" data-v-16cc89a6="">
              <Link href="/sign-in">
                <Button className="bg-primary-500 py-5 px-[35px]">
                  <FaUserAlt className="mr-2 w-3 h-3" />
                  <span>Sign in</span>
                </Button>
              </Link>
            </div>
          </div>
        </div>

        <div
          style={{
            backgroundImage:
              "url(https://streamo.vuejstemplate.com/images/bg/bg-4.jpg)",
          }}
          className="hero-landing h-screen relative before:content-[''] before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-[#000000] before:opacity-60 flex items-center justify-center"
        >
          <div className="container">{children}</div>
        </div>
      </body>
    </html>
  );
}
